import java.util.ArrayList;
import java.util.List;

import acsse.csc2a.model.Warrior;
import acsse.csc2a.tester.PB2Tester;
import acsse.csc2a.model.Mage;
import acsse.csc2a.model.Rogue;
import acsse.csc2a.visitor.AbstractCharacterVisitable;
import acsse.csc2a.visitor.BuffVisitor;

/* |------------------------------------------------|
*
* 				DO NOT EDIT THIS FILE!
* YOU NEED TO MAKE YOUR SOLUTION WORK WITH THIS MAIN
*
*   During marking we may replace this main with a 
*  different one to test the functionality of your
*                  classes
* |------------------------------------------------|
*/

public class Main {

	public static void main(String[] args) {
		List<AbstractCharacterVisitable> characters = new ArrayList<>();
		characters.add(new Warrior(50));
		characters.add(new Mage(50));
		characters.add(new Rogue(9));

		BuffVisitor buffVisitor = new BuffVisitor();
		for (AbstractCharacterVisitable character : characters) {
			character.accept(buffVisitor);
		}

		PB2Tester.Test();
	}
}
/* |------------------------------------------------|
*
* 				DO NOT EDIT THIS FILE!
* YOU NEED TO MAKE YOUR SOLUTION WORK WITH THIS MAIN
*
*   During marking we may replace this main with a 
*  different one to test the functionality of your
*                  classes
* |------------------------------------------------|
*/
